export default {
	VITE_PUBLIC_API_URL: import.meta.env.VITE_PUBLIC_API_URL,
    VITE_PRIVATE_API_URL: import.meta.env.VITE_PRIVATE_API_URL,
    VITE_BASE_API_TIMEOUT: import.meta.env.VITE_BASE_API_TIMEOUT,
    VITE_BASE_ENVIRONTMENT: import.meta.env.VITE_BASE_ENVIRONTMENT,
    VITE_BASE_CLOUDINARY_URL: import.meta.env.VITE_BASE_CLOUDINARY_URL
};