export const COUNTER_INCREMENT = 'COUNTER_INCREMENT';
export const COUNTER_DECREMENT = 'COUNTER_DECREMENT';

export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const VALIDATE_USER = 'VALIDATE_USER';

export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const GET_DETAIL_PRODUCT = 'GET_DETAIL_PRODUCT';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const REMOVE_DETAIL_PRODUCT = 'REMOVE_DETAIL_PRODUCT';

export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_DETAIL_USER = 'GET_DETAIL_USER';
export const CREATE_USER = 'CREATE_USER';
export const EDIT_USER = 'EDIT_USER';
export const DELETE_USER = 'DELETE_USER';